const fs = require('fs');

const md = fs.readFileSync('c:/work/workspaces/investments/investments/reports/2026-03-10/CIS300/CSI300_report_2026-03-10.md', 'utf-8');

function markdownToHtml(md) {
    let html = md;

    // Remove empty signals generated by Python scripts from markdown output to avoid duplication (since we show it in the header)
    html = html.replace(/\*\*Signal:\*\* .*?\n/gi, "");
    html = html.replace(/\*\*Score:\*\* .*?\n/gi, "");

    // Escape HTML entities (but preserve our own tags later)
    html = html.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

    // Enhance headers to be more attractive by pre-pending a decorative span
    html = html.replace(
        /^### (.+)$/gm, 
        '"<h3></h3>"'
    );
    html = html.replace(
        /^## (.+)$/gm, 
        '"<h2><span style=\\"color: var(--accent-blue); margin-right: 8px;\\">//</span> </h2>"'
    );
    html = html.replace(/^# (.+)$/gm, '"<h1></h1>"');

    // Bold / Italic
    html = html.replace(/\*\*(.+?)\*\*/g, '"<strong></strong>"');
    html = html.replace(/\*(.+?)\*/g, '"<em></em>"');

    // Inline code & Links
    html = html.replace(/([^]+)/g, '"<code></code>"');
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '"<a href=\\"\\" target=\\"_blank\\" rel=\\"noopener\\"></a>"');

    // Images
    html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '"<img src=\\"\\" alt=\\"\\" />"');

    // Blockquotes (Apple style callouts)
    html = html.replace(/^&gt; (.+)$/gm, '"<blockquote></blockquote>"');

    // Lists
    html = html.replace(/^- (.+)$/gm, '"<li></li>"');
    html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => '"<ul>"' + match + '"</ul>"');

    // Horizontal rules (styled via CSS)
    html = html.replace(/^---$/gm, '"<hr />"');

    // Paragraphs: wrap loose lines
    html = html.replace(/^(?!<[a-z/])((?!^\s*$).+)$/gm, '"<p></p>"');
    html = html.replace(/<p>\s*<\/p>/g, "");

    return html;
}

console.log(markdownToHtml(md));
