interface MarkdownRendererProps {
    content: string;
}

/**
 * Server-side string replacement markdown-to-HTML fast renderer.
 * Restyled with beautiful syntax highlighting cues via CSS.
 */
export default function MarkdownRenderer({ content }: MarkdownRendererProps) {
    const html = markdownToHtml(content);
    return (
        <div className="report" dangerouslySetInnerHTML={{ __html: html }} />
    );
}

function markdownToHtml(md: string): string {
    let html = md;

    // Remove empty signals generated by Python scripts from markdown output to avoid duplication (since we show it in the header)
    html = html.replace(/\*\*Signal:\*\* .*?\n/gi, "");
    html = html.replace(/\*\*Score:\*\* .*?\n/gi, "");

    // Escape HTML entities (but preserve our own tags later)
    html = html.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

    // Enhance headers to be more attractive by pre-pending a decorative span
    html = html.replace(
        /^### (.+)$/gm, 
        '<h3>$1</h3>'
    );
    html = html.replace(
        /^## (.+)$/gm, 
        '<h2><span style="color: var(--accent-blue); margin-right: 8px;">//</span> $1</h2>'
    );
    html = html.replace(/^# (.+)$/gm, "<h1>$1</h1>");

    // Bold / Italic
    html = html.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    html = html.replace(/\*(.+?)\*/g, "<em>$1</em>");

    // Inline code & Links
    html = html.replace(/`([^`]+)`/g, "<code>$1</code>");
    html = html.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank" rel="noopener">$1</a>');

    // Images
    html = html.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" />');

    // Blockquotes (Apple style callouts)
    html = html.replace(/^&gt; (.+)$/gm, "<blockquote>$1</blockquote>");

    // Tables
    html = convertTables(html);

    // Lists
    html = html.replace(/^- (.+)$/gm, "<li>$1</li>");
    html = html.replace(/(<li>.*<\/li>\n?)+/g, (match) => `<ul>${match}</ul>`);

    // Horizontal rules (styled via CSS)
    html = html.replace(/^---$/gm, "<hr />");

    // Paragraphs: wrap loose lines
    html = html.replace(/^(?!<[a-z/])((?!^\s*$).+)$/gm, "<p>$1</p>");
    html = html.replace(/<p>\s*<\/p>/g, "");

    return html;
}

function convertTables(html: string): string {
    const lines = html.split("\n");
    const result: string[] = [];
    let inTable = false;
    let headerDone = false;

    // Wrapper div for responsive scrolling on mobile
    const startTable = '<div style="overflow-x: auto; -webkit-overflow-scrolling: touch; border-radius: 12px; border: 1px solid var(--border); margin: 24px 0;"><table style="margin: 0;">';
    
    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        const isTableRow = line.startsWith("|") && line.endsWith("|");

        if (isTableRow) {
            const isSeparator = /^\|[\s-:|]+\|$/.test(line);

            if (isSeparator) {
                headerDone = true;
                continue;
            }

            if (!inTable) {
                result.push(startTable);
                inTable = true;
                headerDone = false;
            }

            const cells = line.split("|").filter((c) => c.trim() !== "").map((c) => c.trim());

            if (!headerDone) {
                result.push("<thead><tr>" + cells.map((c) => `<th>${c}</th>`).join("") + "</tr></thead><tbody>");
            } else {
                result.push("<tr>" + cells.map((c) => `<td>${c}</td>`).join("") + "</tr>");
            }
        } else {
            if (inTable) {
                result.push("</tbody></table></div>");
                inTable = false;
                headerDone = false;
            }
            result.push(lines[i]);
        }
    }

    if (inTable) result.push("</tbody></table></div>");
    return result.join("\n");
}
